name = "test-search-worker"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# Test environment configuration
[env.test]
name = "test-search-worker"
# Using default workers.dev domain for testing

# Variables for test environment
[env.test.vars]
ENVIRONMENT = "test"
DEBUG = "true"

# Secrets to be set via wrangler secret put
# wrangler secret put UPSTASH_REDIS_REST_URL --env test
# wrangler secret put UPSTASH_REDIS_REST_TOKEN --env test
# wrangler secret put REDDIT_CLIENT_ID --env test  
# wrangler secret put REDDIT_CLIENT_SECRET --env test
